steps:
  - label: ':construction_worker: Build'
    command: 'mkdir proyecto-react && cd proyecto-react && npm install -g npm@10.2.5 && chmod -R 777 node_modules'
    key: 'build'
    plugins:
      - docker#v3.8.0:
          image: 'node:20.10.0-alpine3.18'
          workdir: '/app'
          environment:
            - 'PORT=3000'
  
  - label: ':white_check_mark: Test'
    command: 'cd proyecto react && chmod -R 777 node_modules && npm test'
    key: 'test'
    plugins:
      - docker#v3.8.0:
          image: 'node:20.10.0-alpine3.18'
          workdir: '/app'
          environment:
            - 'PORT=3000'
    depends_on: 'build'
  
  - label: ':rocket: Deploy'
    command: 'npm start'
    key: 'deploy'
    plugins:
      - docker#v3.8.0:
          image: 'node:20.10.0-alpine3.18'
          workdir: '/app'
          environment:
            - 'PORT=3000'
    depends_on: 'test'
