steps:
  - label: ':construction_worker: Build'
    command: 'npm install'
    plugins:
      - docker#v3.8.0:
          image: 'node:20.10.0-alpine3.18'
          workdir: '/app'
          environment:
            - 'PORT=3000'
  
  - label: ':white_check_mark: Test'
    command: 'npm test'
    plugins:
      - docker#v3.8.0:
          image: 'node:20.10.0-alpine3.18'
          workdir: '/app'
          environment:
            - 'PORT=3000'
    depends_on: 'Construcción'
  
  - label: ':rocket: Deploy'
    command: 'npm start'
    plugins:
      - docker#v3.8.0:
          image: 'node:20.10.0-alpine3.18'
          workdir: '/app'
          environment:
            - 'PORT=3000'
    depends_on: 'Pruebas'
