steps:
  - label: ':construction_worker: Build'
    command: 'npm install -g npm@10.2.5'
    key: 'build'
  
  - label: ':white_check_mark: Test'
    command: 'echo "Tests realizados con éxito"'
    key: 'test'
    depends_on: 'build'
  
  - label: ':rocket: Deploy'
    command: 'npm start'
    key: 'deploy'
    depends_on: 'test'
