steps:
  - label: ':construction_worker: Build'
    command: 'npm install'
    key: 'build'
    plugins:
      - docker:
          image: 'node:lts-buster-slim'
          workdir: '/app'
          environment:
            - 'PORT=3000'
  
  - label: ':white_check_mark: Test'
    command: './scripts/test.sh'
    key: 'test'
    plugins:
      - docker:
          image: 'node:lts-buster-slim'
          workdir: '/app'
          environment:
            - 'PORT=3000'
    depends_on: 'build'
  
  - label: ':rocket: Deploy'
    command: ' ./scripts/deliver.sh'
    key: 'deploy'
    plugins:
      - docker:
          image: 'node:lts-buster-slim'
          workdir: '/app'
          environment:
            - 'PORT=3000'
    depends_on: 'test'
